name: Deploy to development
description: "Deploy to development environment and run pipeline update"

concurrency: "1"

on:
  workflow_dispatch:

  push:
    branches:
      - develop
    paths:
      - "**/*.yml"
      - "**/*.py"
      - "**/*.ipynb"
    
jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: pip install wheel
      - run: pip3 install wheel
      - run: pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/
      
      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
